export { login } from './auth'
export { getUserInfo } from './user'
export { toggleSiderBar, toggleRightPanel } from './app'
export { addBug } from './minitor'
export { changeSetting } from './setting'
